// generated from @vscode/web-custom-data package

import { HTMLAttributes, HTMLTags } from "../types"

const attrValueB = ["true", "false"]
const attrValueU = ["true", "false", "undefined"]
const attrValueO = ["on", "off"]
const attrValueY = ["yes", "no"]
const attrValueW = ["soft", "hard"]
const attrValueD = ["ltr", "rtl", "auto"]
const attrValueM = ["get", "post", "dialog"]
const attrValueFm = ["get", "post"]
const attrValueS = ["row", "col", "rowgroup", "colgroup"]
const attrValueT = ["hidden", "text", "search", "tel", "url", "email", "password", "datetime", "date", "month", "week", "time", "datetime-local", "number", "range", "color", "checkbox", "radio", "file", "submit", "image", "reset", "button"]
const attrValueBt = ["button", "submit", "reset", "menu"]
const attrValueLt = ["1", "a", "A", "i", "I"]
const attrValueEt = ["application/x-www-form-urlencoded", "multipart/form-data", "text/plain"]
const attrValueTk = ["subtitles", "captions", "descriptions", "chapters", "metadata"]
const attrValuePl = ["none", "metadata", "auto"]
const attrValueSh = ["circle", "default", "poly", "rect"]
const attrValueXo = ["anonymous", "use-credentials"]
const attrValueTarget = ["_self", "_blank", "_parent", "_top"]
const attrValueSb = ["allow-forms", "allow-modals", "allow-pointer-lock", "allow-popups", "allow-popups-to-escape-sandbox", "allow-same-origin", "allow-scripts", "allow-top-navigation"]
const attrValueTristate = ["true", "false", "mixed", "undefined"]
const attrValueInputautocomplete = ["additional-name", "address-level1", "address-level2", "address-level3", "address-level4", "address-line1", "address-line2", "address-line3", "bday", "bday-year", "bday-day", "bday-month", "billing", "cc-additional-name", "cc-csc", "cc-exp", "cc-exp-month", "cc-exp-year", "cc-family-name", "cc-given-name", "cc-name", "cc-number", "cc-type", "country", "country-name", "current-password", "email", "family-name", "fax", "given-name", "home", "honorific-prefix", "honorific-suffix", "impp", "language", "mobile", "name", "new-password", "nickname", "off", "on", "organization", "organization-title", "pager", "photo", "postal-code", "sex", "shipping", "street-address", "tel-area-code", "tel", "tel-country-code", "tel-extension", "tel-local", "tel-local-prefix", "tel-local-suffix", "tel-national", "transaction-amount", "transaction-currency", "url", "username", "work"]
const attrValueAutocomplete = ["inline", "list", "both", "none"]
const attrValueCurrent = ["true", "false", "page", "step", "location", "date", "time"]
const attrValueDropeffect = ["copy", "move", "link", "execute", "popup", "none"]
const attrValueInvalid = ["true", "false", "grammar", "spelling"]
const attrValueLive = ["off", "polite", "assertive"]
const attrValueOrientation = ["vertical", "horizontal", "undefined"]
const attrValueRelevant = ["additions", "removals", "text", "all", "additions text"]
const attrValueSort = ["ascending", "descending", "none", "other"]
const attrValueRoles = ["alert", "alertdialog", "button", "checkbox", "dialog", "gridcell", "link", "log", "marquee", "menuitem", "menuitemcheckbox", "menuitemradio", "option", "progressbar", "radio", "scrollbar", "searchbox", "slider", "spinbutton", "status", "switch", "tab", "tabpanel", "textbox", "timer", "tooltip", "treeitem", "combobox", "grid", "listbox", "menu", "menubar", "radiogroup", "tablist", "tree", "treegrid", "application", "article", "cell", "columnheader", "definition", "directory", "document", "feed", "figure", "group", "heading", "img", "list", "listitem", "math", "none", "note", "presentation", "region", "row", "rowgroup", "rowheader", "separator", "table", "term", "text", "toolbar", "banner", "complementary", "contentinfo", "form", "main", "navigation", "region", "search", "doc-abstract", "doc-acknowledgments", "doc-afterword", "doc-appendix", "doc-backlink", "doc-biblioentry", "doc-bibliography", "doc-biblioref", "doc-chapter", "doc-colophon", "doc-conclusion", "doc-cover", "doc-credit", "doc-credits", "doc-dedication", "doc-endnote", "doc-endnotes", "doc-epigraph", "doc-epilogue", "doc-errata", "doc-example", "doc-footnote", "doc-foreword", "doc-glossary", "doc-glossref", "doc-index", "doc-introduction", "doc-noteref", "doc-notice", "doc-pagebreak", "doc-pagelist", "doc-part", "doc-preface", "doc-prologue", "doc-pullquote", "doc-qna", "doc-subtitle", "doc-tip", "doc-toc"]
const attrValueHaspopup = ["true", "false", "menu", "listbox", "tree", "grid", "dialog"]
const attrValueDecoding = ["sync", "async", "auto"]
const attrValueLoading = ["eager", "lazy"]
const attrValueReferrerpolicy = ["no-referrer", "no-referrer-when-downgrade", "origin", "origin-when-cross-origin", "same-origin", "strict-origin", "strict-origin-when-cross-origin", "unsafe-url"]

const globalAttributes: HTMLAttributes = {
	accesskey: 0,
	autocapitalize: 0,
	class: 0,
	contenteditable: 0,
	contextmenu: 0,
	dir: attrValueD,
	draggable: attrValueB,
	dropzone: 0,
	exportparts: 0,
	hidden: 0,
	id: 0,
	inputmode: 0,
	is: 0,
	itemid: 0,
	itemprop: 0,
	itemref: 0,
	itemscope: 0,
	itemtype: 0,
	lang: 0,
	part: 0,
	role: attrValueRoles,
	slot: 0,
	spellcheck: attrValueB,
	style: 0,
	tabindex: 0,
	title: 0,
	translate: attrValueY,
	onabort: 0,
	onblur: 0,
	oncanplay: 0,
	oncanplaythrough: 0,
	onchange: 0,
	onclick: 0,
	oncontextmenu: 0,
	ondblclick: 0,
	ondrag: 0,
	ondragend: 0,
	ondragenter: 0,
	ondragleave: 0,
	ondragover: 0,
	ondragstart: 0,
	ondrop: 0,
	ondurationchange: 0,
	onemptied: 0,
	onended: 0,
	onerror: 0,
	onfocus: 0,
	onformchange: 0,
	onforminput: 0,
	oninput: 0,
	oninvalid: 0,
	onkeydown: 0,
	onkeypress: 0,
	onkeyup: 0,
	onload: 0,
	onloadeddata: 0,
	onloadedmetadata: 0,
	onloadstart: 0,
	onmousedown: 0,
	onmousemove: 0,
	onmouseout: 0,
	onmouseover: 0,
	onmouseup: 0,
	onmousewheel: 0,
	onmouseenter: 0,
	onmouseleave: 0,
	onpause: 0,
	onplay: 0,
	onplaying: 0,
	onprogress: 0,
	onratechange: 0,
	onreset: 0,
	onresize: 0,
	onreadystatechange: 0,
	onscroll: 0,
	onseeked: 0,
	onseeking: 0,
	onselect: 0,
	onshow: 0,
	onstalled: 0,
	onsubmit: 0,
	onsuspend: 0,
	ontimeupdate: 0,
	onvolumechange: 0,
	onwaiting: 0,
	onpointercancel: 0,
	onpointerdown: 0,
	onpointerenter: 0,
	onpointerleave: 0,
	onpointerlockchange: 0,
	onpointerlockerror: 0,
	onpointermove: 0,
	onpointerout: 0,
	onpointerover: 0,
	onpointerup: 0,
	"aria-activedescendant": 0,
	"aria-atomic": attrValueB,
	"aria-autocomplete": attrValueAutocomplete,
	"aria-busy": attrValueB,
	"aria-checked": attrValueTristate,
	"aria-colcount": 0,
	"aria-colindex": 0,
	"aria-colspan": 0,
	"aria-controls": 0,
	"aria-current": attrValueCurrent,
	"aria-describedby": 0,
	"aria-disabled": attrValueB,
	"aria-dropeffect": attrValueDropeffect,
	"aria-errormessage": 0,
	"aria-expanded": attrValueU,
	"aria-flowto": 0,
	"aria-grabbed": attrValueU,
	"aria-haspopup": attrValueHaspopup,
	"aria-hidden": attrValueB,
	"aria-invalid": attrValueInvalid,
	"aria-label": 0,
	"aria-labelledby": 0,
	"aria-level": 0,
	"aria-live": attrValueLive,
	"aria-modal": attrValueB,
	"aria-multiline": attrValueB,
	"aria-multiselectable": attrValueB,
	"aria-orientation": attrValueOrientation,
	"aria-owns": 0,
	"aria-placeholder": 0,
	"aria-posinset": 0,
	"aria-pressed": attrValueTristate,
	"aria-readonly": attrValueB,
	"aria-relevant": attrValueRelevant,
	"aria-required": attrValueB,
	"aria-roledescription": 0,
	"aria-rowcount": 0,
	"aria-rowindex": 0,
	"aria-rowspan": 0,
	"aria-selected": attrValueU,
	"aria-setsize": 0,
	"aria-sort": attrValueSort,
	"aria-valuemax": 0,
	"aria-valuemin": 0,
	"aria-valuenow": 0,
	"aria-valuetext": 0,
	"aria-details": 0,
	"aria-keyshortcuts": 0,
}

const tags: HTMLTags = {
	html: {
		manifest: 0,
		version: 0,
		xmlns: 0,
	},
	head: {
		profile: 0,
	},
	title: {},
	base: {
		href: 0,
		target: attrValueTarget,
	},
	link: {
		href: 0,
		crossorigin: attrValueXo,
		rel: 0,
		media: 0,
		hreflang: 0,
		type: 0,
		sizes: 0,
		as: 0,
		importance: 0,
		integrity: 0,
		referrerpolicy: 0,
	},
	meta: {
		name: 0,
		"http-equiv": 0,
		content: 0,
		charset: 0,
		scheme: 0,
	},
	style: {
		media: 0,
		nonce: 0,
		type: 0,
		scoped: 0,
	},
	body: {
		onafterprint: 0,
		onbeforeprint: 0,
		onbeforeunload: 0,
		onhashchange: 0,
		onlanguagechange: 0,
		onmessage: 0,
		onoffline: 0,
		ononline: 0,
		onpagehide: 0,
		onpageshow: 0,
		onpopstate: 0,
		onstorage: 0,
		onunload: 0,
		alink: 0,
		background: 0,
		bgcolor: 0,
		bottommargin: 0,
		leftmargin: 0,
		link: 0,
		onredo: 0,
		onundo: 0,
		rightmargin: 0,
		text: 0,
		topmargin: 0,
		vlink: 0,
	},
	article: {},
	section: {},
	nav: {},
	aside: {},
	h1: {},
	h2: {},
	h3: {},
	h4: {},
	h5: {},
	h6: {},
	header: {},
	footer: {},
	address: {},
	p: {},
	hr: {
		align: 0,
		color: 0,
		noshade: 0,
		size: 0,
		width: 0,
	},
	pre: {
		cols: 0,
		width: 0,
		wrap: 0,
	},
	blockquote: {
		cite: 0,
	},
	ol: {
		reversed: 0,
		start: 0,
		type: attrValueLt,
		compact: 0,
	},
	ul: {
		compact: 0,
	},
	li: {
		value: 0,
		type: 0,
	},
	dl: {},
	dt: {},
	dd: {
		nowrap: 0,
	},
	figure: {},
	figcaption: {},
	main: {},
	div: {},
	a: {
		href: 0,
		target: attrValueTarget,
		download: 0,
		ping: 0,
		rel: 0,
		hreflang: 0,
		type: 0,
		referrerpolicy: 0,
	},
	em: {},
	strong: {},
	small: {},
	s: {},
	cite: {},
	q: {
		cite: 0,
	},
	dfn: {},
	abbr: {},
	ruby: {},
	rb: {},
	rt: {},
	rp: {},
	time: {
		datetime: 0,
	},
	code: {},
	var: {},
	samp: {},
	kbd: {},
	sub: {},
	sup: {},
	i: {},
	b: {},
	u: {},
	mark: {},
	bdi: {},
	bdo: {
	},
	span: {},
	br: {
		clear: 0,
	},
	wbr: {},
	ins: {
		cite: 0,
		datetime: 0,
	},
	del: {
		cite: 0,
		datetime: 0,
	},
	picture: {},
	img: {
		alt: 0,
		src: 0,
		srcset: 0,
		crossorigin: attrValueXo,
		usemap: 0,
		ismap: 0,
		width: 0,
		height: 0,
		decoding: attrValueDecoding,
		loading: attrValueLoading,
		referrerpolicy: attrValueReferrerpolicy,
		sizes: 0,
		importance: 0,
		intrinsicsize: 0,
	},
	iframe: {
		src: 0,
		srcdoc: 0,
		name: 0,
		sandbox: attrValueSb,
		seamless: 0,
		allowfullscreen: 0,
		width: 0,
		height: 0,
		allow: 0,
		allowpaymentrequest: 0,
		csp: 0,
		importance: 0,
		referrerpolicy: 0,
	},
	embed: {
		src: 0,
		type: 0,
		width: 0,
		height: 0,
	},
	object: {
		data: 0,
		type: 0,
		typemustmatch: 0,
		name: 0,
		usemap: 0,
		form: 0,
		width: 0,
		height: 0,
		archive: 0,
		border: 0,
		classid: 0,
		codebase: 0,
		codetype: 0,
		declare: 0,
		standby: 0,
	},
	param: {
		name: 0,
		value: 0,
		type: 0,
		valuetype: 0,
	},
	video: {
		src: 0,
		crossorigin: attrValueXo,
		poster: 0,
		preload: attrValuePl,
		autoplay: 0,
		mediagroup: 0,
		loop: 0,
		muted: 0,
		controls: 0,
		width: 0,
		height: 0,
	},
	audio: {
		src: 0,
		crossorigin: attrValueXo,
		preload: attrValuePl,
		autoplay: 0,
		mediagroup: 0,
		loop: 0,
		muted: 0,
		controls: 0,
	},
	source: {
		src: 0,
		type: 0,
		sizes: 0,
		srcset: 0,
		media: 0,
	},
	track: {
		default: 0,
		kind: attrValueTk,
		label: 0,
		src: 0,
		srclang: 0,
	},
	map: {
		name: 0,
	},
	area: {
		alt: 0,
		coords: 0,
		shape: attrValueSh,
		href: 0,
		target: attrValueTarget,
		download: 0,
		ping: 0,
		rel: 0,
		hreflang: 0,
		type: 0,
	},
	table: {
		border: 0,
		align: 0,
	},
	caption: {
		align: 0,
	},
	colgroup: {
		span: 0,
		align: 0,
	},
	col: {
		span: 0,
		align: 0,
	},
	tbody: {
		align: 0,
	},
	thead: {
		align: 0,
	},
	tfoot: {
		align: 0,
	},
	tr: {
		align: 0,
	},
	td: {
		colspan: 0,
		rowspan: 0,
		headers: 0,
		abbr: 0,
		align: 0,
		axis: 0,
		bgcolor: 0,
	},
	th: {
		colspan: 0,
		rowspan: 0,
		headers: 0,
		scope: attrValueS,
		sorted: 0,
		abbr: 0,
		align: 0,
		axis: 0,
		bgcolor: 0,
	},
	form: {
		"accept-charset": 0,
		action: 0,
		autocomplete: attrValueO,
		enctype: attrValueEt,
		method: attrValueM,
		name: 0,
		novalidate: 0,
		target: attrValueTarget,
		accept: 0,
	},
	label: {
		form: 0,
		for: 0,
	},
	input: {
		accept: 0,
		alt: 0,
		autocomplete: attrValueInputautocomplete,
		autofocus: 0,
		checked: 0,
		dirname: 0,
		disabled: 0,
		form: 0,
		formaction: 0,
		formenctype: attrValueEt,
		formmethod: attrValueFm,
		formnovalidate: 0,
		formtarget: 0,
		height: 0,
		list: 0,
		max: 0,
		maxlength: 0,
		min: 0,
		minlength: 0,
		multiple: 0,
		name: 0,
		pattern: 0,
		placeholder: 0,
		readonly: 0,
		required: 0,
		size: 0,
		src: 0,
		step: 0,
		type: attrValueT,
		value: 0,
		width: 0,
	},
	button: {
		autofocus: 0,
		disabled: 0,
		form: 0,
		formaction: 0,
		formenctype: attrValueEt,
		formmethod: attrValueFm,
		formnovalidate: 0,
		formtarget: 0,
		name: 0,
		type: attrValueBt,
		value: 0,
		autocomplete: 0,
	},
	select: {
		autocomplete: attrValueInputautocomplete,
		autofocus: 0,
		disabled: 0,
		form: 0,
		multiple: 0,
		name: 0,
		required: 0,
		size: 0,
	},
	datalist: {},
	optgroup: {
		disabled: 0,
		label: 0,
	},
	option: {
		disabled: 0,
		label: 0,
		selected: 0,
		value: 0,
	},
	textarea: {
		autocomplete: attrValueInputautocomplete,
		autofocus: 0,
		cols: 0,
		dirname: 0,
		disabled: 0,
		form: 0,
		maxlength: 0,
		minlength: 0,
		name: 0,
		placeholder: 0,
		readonly: 0,
		required: 0,
		rows: 0,
		wrap: attrValueW,
	},
	output: {
		for: 0,
		form: 0,
		name: 0,
	},
	progress: {
		value: 0,
		max: 0,
	},
	meter: {
		value: 0,
		min: 0,
		max: 0,
		low: 0,
		high: 0,
		optimum: 0,
		form: 0,
	},
	fieldset: {
		disabled: 0,
		form: 0,
		name: 0,
	},
	legend: {},
	details: {
		open: 0,
	},
	summary: {},
	dialog: {
		open: 0,
	},
	script: {
		src: 0,
		type: 0,
		charset: 0,
		async: 0,
		defer: 0,
		crossorigin: attrValueXo,
		nonce: 0,
		integrity: 0,
		nomodule: 0,
		referrerpolicy: 0,
		text: 0,
	},
	noscript: {},
	template: {},
	canvas: {
		width: 0,
		height: 0,
		"moz-opaque": 0,
	},
	slot: {
		name: 0,
	},
	data: {
		value: 0,
	},
	hgroup: {},
	menu: {},
}

export { globalAttributes, tags }
